# Импорт данных и библиотек

In [56]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings

warnings.filterwarnings('ignore')

In [2]:
data = pd.read_excel('Analytic_test.xlsx', header=1) # читаем файл и устанавливаем название столбцов из строки 1
data.drop(columns='Unnamed: 0', inplace=True) # удаляем ненужный признак

data.head() # смотрим первые 5 наблюдений

,HID,active_Red,has_Green_id,has_Black_id,has_Blue_id,Blue_activity_count,Blue_gmv_total,Green_gvm_total,Green_gvm_order_count,Black_gvm_total,...,Blue_android,Red_apple,Green_apple,Black_apple,Blue_apple,is_msk,Red_web,Green_web,Black_web,Blue_web
0,00003c7fb5e57ce673f1801f3679f5c25,0.0,0.0,0.0,1.0,2.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,00006b602533083e3bebfcbff08613931,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
2,0000736c3f76339196cb1cc759b8363b,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
3,00009bdcc5307b38efde8690b8bd658e,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
4,0000bc3186b7b31d9b35d3fbbb250b9f8,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

# Работа с пропусками

In [3]:
data.isna().mean() # посмотрим среднее число пропусков по каждому признаку

HID                      0.00000
active_Red               0.00000
has_Green_id             0.00000
has_Black_id             0.00000
has_Blue_id              0.00000
Blue_activity_count      0.00000
Blue_gmv_total           0.00001
Green_gvm_total          0.00000
Green_gvm_order_count    0.00000
Black_gvm_total          0.00000
Black_gvm_order_count    0.00000
Red_android              0.00000
Green_android            0.00000
Black_android            0.00000
Blue_android             0.00000
Red_apple                0.00000
Green_apple              0.00000
Black_apple              0.00000
Blue_apple               0.00000
is_msk                   0.00000
Red_web                  0.00000
Green_web                0.00000
Black_web                0.00000
Blue_web                 0.00000
dtype: float64

**Нетрудно видеть, что пропусков практически нет.**

In [4]:
data.fillna(0, inplace=True) # заполним пропуски нулями, так как их немного это особо ни на что не повлияет

data.sample(5) # берём случайные 5 наблюдений

,HID,active_Red,has_Green_id,has_Black_id,has_Blue_id,Blue_activity_count,Blue_gmv_total,Green_gvm_total,Green_gvm_order_count,Black_gvm_total,...,Blue_android,Red_apple,Green_apple,Black_apple,Blue_apple,is_msk,Red_web,Green_web,Black_web,Blue_web
65345,17d91125bbb635f5373b3790b25bb67c5e,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
80698,1d6ce57509f033733060301995fd316b,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
56453,1259b3bc9b857dbd25b003e978777739ee,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
69389,19558b7618ee3b03b9d1b097f503c635,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
41532,0f3b53dd077739e25c70125ede1b3f3de8,0.0,0.0,0.0,1.0,8.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

# Посмотрим на основные числовые характеристки признаков

In [5]:
data.describe()

,active_Red,has_Green_id,has_Black_id,has_Blue_id,Blue_gmv_total,Green_gvm_total,Black_gvm_total,Red_android,Green_android,Black_android,Blue_android,Red_apple,Green_apple,Black_apple,Blue_apple,is_msk,Red_web,Green_web,Black_web,Blue_web
count,100000.00000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.00000,100000.00000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.00000,100000.000000,100000.000000,100000.000000,100000.000000,100000.00000
mean,0.55874,0.008900,0.010840,0.138010,2.461140,59.934200,94.873080,0.32133,0.00546,0.010770,0.080470,0.108740,0.006160,0.017820,0.04646,0.119210,0.671080,0.001980,0.014610,0.10640
std,0.49654,0.094344,0.104032,0.360645,126.674085,1230.671036,1699.422723,0.46699,0.07369,0.103219,0.272021,0.311314,0.078244,0.132297,0.21048,0.324037,0.469823,0.044453,0.119986,0.30835
min,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.00000
25%,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.00000
50%,1.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,1.000000,0.000000,0.000000,0.00000
75%,1.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.00000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,1.000000,0.000000,0.000000,0.00000
max,1.00000,2.000000,2.000000,4.000000,32302.000000,94106.000000,188252.000000,1.00000,1.00000,1.000000,1.000000,1.000000,1.000000,1.000000,1.00000,1.000000,1.000000,1.000000,1.000000,1.00000

**Выводы:**

- Замечаем что у признаков `has_Green_id`, `has_Black_id`, `has_Blue_id` есть значения 2 и 4, чего быть не может по смыслу этих признаков, исправим это далее, на этапе предобработки
- Также замечаем огромные стандартные отклонения у признаков `Blue_gmv_total`, `Green_gvm_total`, `Black_gvm_total`, что говорит о неоднородостни данных (так как при этом у этих признаков небольше средние, то коэффициент вариации будет высоким => данные не однородны)
- Ещё можно заметить что по признаку `Blue_activity_count` нет статистик, это может значить что он не числовой.

# Предобработка

Посмотрим на уникальные значения в столбцах `has_Green_id`, `has_Black_id`, `has_Blue_id`.

In [6]:
print(pd.unique(data.has_Green_id))
print(pd.unique(data.has_Black_id))
print(pd.unique(data.has_Blue_id))

[0. 1. 2.]
[0. 1. 2.]
[1. 0. 2. 3. 4.]

Напишем функцию которая заменяет все значения большие 1 на единицу, а 0 оставляет нулём.

In [7]:
def replacer(n: int) -> int:
    if n > 1:
        return 1
    
    return 0

Исправим значения признаков `has_Green_id`, `has_Black_id`, `has_Blue_id`, применив вышенаписанную функцию к этим столбцам.

In [8]:
data.has_Green_id = data.has_Green_id.apply(replacer)
data.has_Black_id = data.has_Black_id.apply(replacer)
data.has_Blue_id = data.has_Blue_id.apply(replacer)

Переименуем столбец `active_Red`  в `has_Red_id`, так как по принимаемым значениям и названию можно думать что это он и есть. Также исправим опечатки в `Green_gvm_total` и `Black_gvm_total`.

In [9]:
data.rename(columns={'active_Red': 'has_Red_id', 
                     'Green_gvm_total': 'Green_gmv_total', 
                     'Black_gvm_total': 'Black_gmv_total'}, 
            inplace=True)

data.tail(5) # смотрим на последние 5 наблюдений

,HID,has_Red_id,has_Green_id,has_Black_id,has_Blue_id,Blue_activity_count,Blue_gmv_total,Green_gmv_total,Green_gvm_order_count,Black_gmv_total,...,Blue_android,Red_apple,Green_apple,Black_apple,Blue_apple,is_msk,Red_web,Green_web,Black_web,Blue_web
99995,32555ec33d762588db3253b063525f03b58f,0.0,0,0,0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0
99996,3255600b525b2598b37775fb3b25b3397bbb,1.0,0,0,0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
99997,325563dbbb35c393be38c5c79373ed180,1.0,0,0,0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
99998,3255650825570bcc93bc9b076b0bfbb25e6,0.0,0,0,0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
99999,325566ec18c0db59083f5f6bb1b5f93d5,0.0,0,0,0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0

Посмотрим на уникальные значения признака `Blue_activity_count`.

In [10]:
set(data.Blue_activity_count)

{'0.0',
 '1.0',
 '10.0',
 '100.0',
 '101.0',
 '11.0',
 '111.0',
 '119.0',
 '12.0',
 '13.0',
 '14.0',
 '15.0',
 '16.0',
 '17.0',
 '18.0',
 '19.0',
 '2.0',
 '20.0',
 datetime.datetime(2019, 5, 1, 0, 0),
 datetime.datetime(2019, 5, 3, 0, 0),
 datetime.datetime(2019, 5, 4, 0, 0),
 datetime.datetime(2019, 5, 6, 0, 0),
 datetime.datetime(2019, 5, 7, 0, 0),
 '21.0',
 '22.0',
 '23.0',
 '237.0',
 '24.0',
 '25.0',
 '26.0',
 '27.0',
 '28.0',
 '29.0',
 '3.0',
 '30.0',
 '31.0',
 '32.0',
 '33.0',
 '34.0',
 '35.0',
 '36.0',
 '37.0',
 '38.0',
 '39.0',
 '4.0',
 '40.0',
 '41.0',
 '42.0',
 '43.0',
 '44.0',
 '45.0',
 '46.0',
 '47.0',
 '49.0',
 '5.0',
 '51.0',
 '53.0',
 '59.0',
 '6.0',
 '63.0',
 '66.0',
 '67.0',
 '7.0',
 '71.0',
 '72.0',
 '74.0',
 '8.0',
 '9.0',
 '90.0'}

Видно что там есть как строки, так и даты. Напишем функцию переводящую строки в целые числа, а дату заменяет на 0, потому что если даты переводить в числа, то получатся либо дробные числа (чего быть не может по сути признака), а если переводить в Unix формат (количество секунд от первого января 1970 года) то получится черезчур большое и нереалистичное число.

In [11]:
def converter(el) -> int:
    if isinstance(el, str):
        return int(el.split('.')[0])

    return 0

In [12]:
data.Blue_activity_count = data.Blue_activity_count.apply(converter)

# Предсказание признаков

Так как по некоторым компаниям отсутствует часть их призаков, попробуем спрогнозировать эти значения с помощью машинного обучения.

Значения признака `comp_activity_count` есть только у компании `Blue`, поэтому предсказывать этот признак будем по данным о компании `Blue`, на основании признаков которые есть у всех компаний.

In [47]:
X_Red = data[['has_Red_id', 'Red_android', 'Red_apple', 'Red_web', 'is_msk']]
X_Green = data[['has_Green_id', 'Green_android', 'Green_apple', 'Green_web', 'is_msk']]
X_Black = data[['has_Black_id', 'Black_android', 'Black_apple', 'Black_web', 'is_msk']]

X_Blue = data[['has_Blue_id', 'Blue_android', 'Blue_apple', 'Blue_web', 'is_msk']]
y_Blue = data.Blue_activity_count

Разделим данные на тестовую и тренировочную выборку.

In [48]:
from sklearn.model_selection import train_test_split

X_Blue_train, X_Blue_test, y_Blue_train, y_Blue_test = train_test_split(X_Blue, y_Blue, test_size=0.25, random_state=42)

По своей сути это признак принимающий натуральные значения, поэтому будем строить регрессию с L1 регуляризацией (коеф. регуляризации возьмём 0.0001), в качестве функционала качества возьмём MSE, а затем просто округлим предсказанные значения если они окажутся не целочисленными.

In [54]:
from sklearn.linear_model import Lasso
from sklearn.metrics import mean_squared_error

ridge_model1 = Lasso(0.0001)

ridge_model1.fit(X_Blue_train, y_Blue_train)
y_Blue_pred = ridge_model1.predict(X_Blue_test).astype(int)

print(mean_squared_error(y_Blue_pred, y_Blue_test))

7.10472

Получили довольно хорошоее значение MSE, поэтому будем применять эту модель для предсказания этого призанка у других компаний.

In [62]:
data['Red_activity_count'] = ridge_model1.predict(X_Red).astype(int)
data['Green_activity_count'] = ridge_model1.predict(X_Green).astype(int)
data['Black_activity_count'] = ridge_model1.predict(X_Black).astype(int)

Аналогичным образом, но уже на основании данных о компаниях `Green` и `Black` предскажем признак `comp_gvm_order_count` для компаний `Red` и `Blue`.

In [85]:
X_Red = np.matrix(data[['has_Red_id', 'Red_activity_count', 'Red_android', 'Red_apple', 'Red_web', 'is_msk']])
X_Blue = np.matrix(data[['has_Blue_id', 'Blue_activity_count', 'Blue_android', 'Blue_apple', 'Blue_web', 'is_msk']])
X_Green = np.matrix(data[['has_Green_id', 'Green_activity_count', 'Green_android', 'Green_apple', 'Green_web', 'is_msk']])
X_Black = np.matrix(data[['has_Black_id', 'Black_activity_count', 'Black_android', 'Black_apple', 'Black_web', 'is_msk']])

X_Green_and_Black = np.vstack((X_Green, X_Black))

y_Green = data.Green_gvm_order_count.apply(converter)
y_Black = data.Black_gvm_order_count.apply(converter)

y_Green_and_Black = np.hstack((y_Green, y_Black))

y_Green_and_Black

X_Green_and_Black_train, X_Green_and_Black_test, y_Green_and_Black_train, y_Green_and_Black_test = train_test_split(X_Green_and_Black, y_Green_and_Black, test_size=0.25, random_state=42)

ridge_model2 = Lasso(0.0001)

ridge_model2.fit(X_Green_and_Black_train, y_Green_and_Black_train)
y_Green_and_Black_pred = ridge_model2.predict(X_Green_and_Black_test).astype(int)

print(mean_squared_error(y_Green_and_Black_pred, y_Green_and_Black_test))

1.19722

Опять же таки, ошибка небольшая, поэтому будем использовать эту модель для предсказания признаков.

In [87]:
data['Red_gvm_order_count'] = ridge_model2.predict(X_Red).astype(int)
data['Blue_gvm_order_count'] = ridge_model2.predict(X_Blue).astype(int)

Осталось заполнить последний недостающий признак для компании `Red`, будем использовать данные по всей выборке.

In [124]:
X_Red = np.matrix(data[['has_Red_id', 'Red_gvm_order_count', 'Red_activity_count', 'Red_android', 'Red_apple', 'Red_web', 'is_msk']])
X_Blue = np.matrix(data[['has_Blue_id', 'Blue_gvm_order_count', 'Blue_activity_count', 'Blue_android', 'Blue_apple', 'Blue_web', 'is_msk']])
X_Green = np.matrix(data[['has_Green_id', 'Green_gvm_order_count', 'Green_activity_count', 'Green_android', 'Green_apple', 'Green_web', 'is_msk']])
X_Black = np.matrix(data[['has_Black_id', 'Black_gvm_order_count', 'Black_activity_count', 'Black_android', 'Black_apple', 'Black_web', 'is_msk']])

X_all_except_Red = np.vstack((X_Blue, X_Green, X_Black))

f = pd.DataFrame(X_all_except_Red)
print(set(f.iloc[:, 1]))

y_Blue = data.Blue_gmv_total
y_Green = data.Green_gmv_total
y_Black = data.Black_gmv_total

y_all_except_Red = np.hstack((y_Blue, y_Green, y_Black))

X_all_except_Red_train, X_all_except_Red_test, y_all_except_Red_train, y_all_except_Red_test = train_test_split(X_all_except_Red, y_all_except_Red, test_size=0.25, random_state=42)

# не успел доделать, так как проблема с тем что есть timestamp в признаке comp_gvm_order_count

{0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0, 11.0, 12.0, 13.0, 14.0, 15.0, 16.0, 17.0, 18.0, 19.0, 20.0, 21.0, 22.0, 23.0, 24.0, 25.0, 26.0, 27.0, 28.0, 29.0, 30.0, 31.0, 32.0, 33.0, 34.0, 35.0, 36.0, 37.0, 38.0, 39.0, 40.0, 41.0, 42.0, 43.0, 44.0, 45.0, 46.0, 47.0, '37.0', 49.0, 50.0, 51.0, '45.0', 53.0, 54.0, 55.0, 56.0, 57.0, 58.0, 59.0, 60.0, 61.0, 62.0, '32.0', 64.0, 65.0, 66.0, '36.0', 69.0, 70.0, '43.0', 72.0, 81.0, '25.0', '30.0', 85.0, 87.0, '56.0', 91.0, datetime.datetime(2019, 5, 4, 0, 0), 96.0, 97.0, 98.0, 99.0, '42.0', 103.0, 122.0, '18.0', '101.0', '29.0', '65.0', 136.0, 137.0, '63.0', '40.0', '88.0', 152.0, '20.0', '24.0', 161.0, '49.0', '10.0', '23.0', '114.0', '3.0', '82.0', '35.0', datetime.datetime(2019, 5, 2, 0, 0), '33.0', '28.0', '11.0', datetime.datetime(2019, 5, 6, 0, 0), '39.0', '16.0', '6.0', '52.0', '14.0', '5.0', '4.0', 322.0, '75.0', '60.0', '7.0', '26.0', '12.0', '15.0', '21.0', '168.0', '51.0', '108.0', '17.0', '85.0', '84.0', '69.0', '1.0', '64.0', '127.0', '78.0', '125.0', '19.0', '38.0', '13.0', '34.0', '22.0', '0.0', '50.0', '100.0', '76.0', '83.0', '2.0', '62.0', '27.0', '9.0', '8.0', '31.0'}

# Визуализация

Не успел( Но пример моих визуализаций можно посмотреть по ссылке, на моём гитхабе: https://github.com/LexusShabunya/DataAnalysys/blob/main/EDA.ipynb